M48
; DRILL file {KiCad 7.0.5-0} date 2024 January 05, Friday 10:03:26
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-05T10:03:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X1.8566Y1.0504
X1.8566Y-1.0496
T2
X-1.5536Y-1.2
X-1.2354Y-1.5182
T0
M30
